spring:
  data:
    mongodb:
      uri: mongodb+srv://spranchal864_db_user:eODVF2YfdJpmHk72@cluster0.3mev3q1.mongodb.net/?appName=Cluster0
      database: journaldb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: spranchal864@gmail.com
    password: envo itga vamu wdmy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      
server:
  port: 8080
  servlet:
    context-path: /journal

weather:
  api:
    key: 8ad995b87e1b4e7e889134610261203